// src/lib/noteAI.js
// ✅ AI Note Analysis — Supabase Edge Function (server-side AI)
// ✅ Single authoritative usage check via consumeAiUsage (daily_usage + plan limits)
// ✅ Graceful fallback to local analysis when AI provider unavailable
// ✅ Persists ai_payload to notes table

import { supabase, supabaseReady } from "./supabaseClient";
import { consumeAiUsage } from "./usage";
import { callEdgeFunction } from "./edgeFunctions";

const NOTES_TABLE = "notes";
const MIN_CHARS_FOR_AUTO = 20;
const COOLDOWN_MS = 30_000;

// In-memory cooldown tracker (noteId -> timestamp)
const lastAnalyzed = new Map();

export function shouldAutoAnalyze(noteBody, noteId) {
  if (!noteBody || noteBody.trim().length < MIN_CHARS_FOR_AUTO) return false;

  const last = lastAnalyzed.get(noteId);
  if (last && Date.now() - last < COOLDOWN_MS) return false;

  return true;
}

export async function analyzeNote({ noteId, userId, title, body, isManual = false }) {
  if (!body || body.trim().length < MIN_CHARS_FOR_AUTO) return null;

  // 1) Enforce usage limits (single source of truth)
  if (supabaseReady && supabase && userId) {
    try {
      const usageRes = await consumeAiUsage(userId, "ai_summaries", 1);

      if (!usageRes?.success) {
        return {
          error: true,
          limitReached: true,
          message: "Daily AI limit reached. Upgrade to continue.",
        };
      }
    } catch (err) {
      console.warn("Usage check failed (continuing):", err);
    }
  }

  // 2) Run analysis (Edge → fallback)
  let raw;
  try {
    raw = await callEdgeFunction("analyze-note", {
      title: title || "Untitled",
      body: body || "",
    });
  } catch (err) {
    console.warn("Edge unavailable, using local analysis:", err);
    raw = generateLocalAnalysis({ title, body });
  }

  // 3) Normalize result shape
  const analysis = normalizeAnalysis(raw);
  const now = new Date().toISOString();

  const aiPayload = {
    summary: analysis.summary || null,
    keyPoints: analysis.keyPoints || [],
    actionItems: analysis.actionItems || [],
    sentiment: analysis.sentiment || "neutral",
    topics: analysis.topics || [],
    SmartHighlights: analysis.keyPoints || [],
    SmartTasks: (analysis.actionItems || []).map((text, i) => ({
      id: `task-${i}`,
      text,
      done: false,
    })),
    SmartSchedule: analysis.SmartSchedule ?? null,
    wordCount: (body || "").split(/\s+/).filter(Boolean).length,
    generatedAt: now,
    model: analysis.model || "local-analysis",
    isAutoGenerated: !isManual,
  };

  // 4) Persist to DB
  if (supabaseReady && supabase && userId && noteId) {
    try {
      await supabase
        .from(NOTES_TABLE)
        .update({
          ai_payload: aiPayload,
          ai_generated_at: now,
          ai_model: aiPayload.model,
        })
        .eq("id", noteId)
        .eq("user_id", userId);
    } catch (err) {
      console.warn("Failed to persist AI payload:", err);
    }

    // Activity log (non-blocking)
    try {
      await supabase.rpc("log_activity_event", {
        p_user_id: userId,
        p_event_type: "ai_summary",
        p_title: `AI analyzed note: ${(title || "Untitled").slice(0, 50)}`,
        p_metadata: {
          note_id: noteId,
          auto: !isManual,
          word_count: aiPayload.wordCount,
          model: aiPayload.model,
        },
      });
    } catch {}
  }

  lastAnalyzed.set(noteId, Date.now());
  return aiPayload;
}

// ─── Result normalization ──────────────────────────────────────

function normalizeAnalysis(data) {
  const smartHighlights = Array.isArray(data?.SmartHighlights) ? data.SmartHighlights : null;
  const smartTasks = Array.isArray(data?.SmartTasks) ? data.SmartTasks : null;

  const keyPoints =
    smartHighlights ||
    (Array.isArray(data?.keyPoints) ? data.keyPoints : []) ||
    [];

  const actionItems =
    (smartTasks
      ? smartTasks.map((t) => (typeof t === "string" ? t : t?.text)).filter(Boolean)
      : null) ||
    (Array.isArray(data?.actionItems) ? data.actionItems : []) ||
    [];

  return {
    summary: data?.summary || "",
    keyPoints,
    actionItems,
    SmartSchedule: data?.SmartSchedule ?? null,
    sentiment: data?.sentiment || "neutral",
    topics: Array.isArray(data?.topics) ? data.topics : [],
    model: data?.model || "local-analysis",
  };
}

function generateLocalAnalysis({ title, body }) {
  const text = `${title || ""} ${body || ""}`.trim();
  const words = text.split(/\s+/).filter(Boolean);
  const sentences = text.split(/[.!?]+/).map((s) => s.trim()).filter((s) => s.length > 5);

  const summary = (sentences.slice(0, 3).join(". ") + (sentences.length ? "." : "")).trim();
  const keyPoints = sentences.slice(0, 5);

  const actionItems = sentences
    .filter((s) => /\b(need to|should|must|todo|action|next step|follow up|fix|review|send|submit)\b/i.test(s))
    .slice(0, 6);

  return {
    summary,
    keyPoints,
    actionItems,
    sentiment: "neutral",
    topics: words.slice(0, 8).map((w) => w.toLowerCase()),
    model: "notestream-local-v1",
  };
}
// ═══════════════════════════════════════════════════════════════════
// REWRITE — calls the rewrite-note Edge Function
// ═══════════════════════════════════════════════════════════════════
//
// Modes: "tighten" | "clarify" | "polish"
//
// Returns on success:
//   { rewritten: string, mode, model, generatedAt }
// Returns on failure:
//   { error: true, message, limitReached? }
//
// Unlike analyzeNote(), this does NOT persist to the DB. The frontend
// shows the rewrite in a diff modal and only commits if the user clicks
// Apply — at which point the regular updateNote() path takes over.
// Persisting unconditionally would commit suggestions the user never
// accepted.
export async function rewriteNote({ userId, title, body, mode = "polish" }) {
  if (!body || body.trim().length < 20) {
    return {
      error: true,
      message: "Add at least 20 characters of content before rewriting.",
    };
  }

  // Usage check — same bucket as document-level synthesis since rewrites
  // are comparable in cost / cadence to document operations.
  if (supabaseReady && supabase && userId) {
    try {
      const usageRes = await consumeAiUsage(userId, "document_synth", 1);
      if (!usageRes?.success) {
        return {
          error: true,
          limitReached: true,
          message: "Daily AI limit reached. Upgrade to continue.",
        };
      }
    } catch (err) {
      console.warn("Usage check failed (continuing):", err);
    }
  }

  let raw;
  try {
    raw = await callEdgeFunction("rewrite-note", {
      title: title || "Untitled",
      body: body || "",
      mode,
    });
  } catch (err) {
    console.warn("rewrite-note edge unavailable:", err);
    return { error: true, message: err?.message || "AI rewrite failed." };
  }

  if (!raw || raw.error || !raw.rewritten) {
    return {
      error: true,
      message: raw?.error
        ? `Rewrite failed: ${raw.error}`
        : "Empty AI response.",
    };
  }

  return {
    rewritten: String(raw.rewritten),
    mode: raw.mode || mode,
    model: raw.model || "unknown",
    generatedAt: raw.generatedAt || new Date().toISOString(),
  };
}

// ═══════════════════════════════════════════════════════════════════
// EXPAND — calls the expand-note Edge Function
// ═══════════════════════════════════════════════════════════════════
//
// Modes: "detail" | "examples" | "context"
//
// Returns on success:
//   { expanded: string, mode, model, generatedAt }
// Returns on failure:
//   { error: true, message, limitReached? }
//
// Same non-persisting contract as rewriteNote — the user reviews in a
// diff modal and chooses whether to commit.
export async function expandNote({ userId, title, body, mode = "detail" }) {
  if (!body || body.trim().length < 20) {
    return {
      error: true,
      message: "Add at least 20 characters of content before expanding.",
    };
  }

  if (supabaseReady && supabase && userId) {
    try {
      const usageRes = await consumeAiUsage(userId, "document_synth", 1);
      if (!usageRes?.success) {
        return {
          error: true,
          limitReached: true,
          message: "Daily AI limit reached. Upgrade to continue.",
        };
      }
    } catch (err) {
      console.warn("Usage check failed (continuing):", err);
    }
  }

  let raw;
  try {
    raw = await callEdgeFunction("expand-note", {
      title: title || "Untitled",
      body: body || "",
      mode,
    });
  } catch (err) {
    console.warn("expand-note edge unavailable:", err);
    return { error: true, message: err?.message || "AI expand failed." };
  }

  if (!raw || raw.error || !raw.expanded) {
    return {
      error: true,
      message: raw?.error
        ? `Expand failed: ${raw.error}`
        : "Empty AI response.",
    };
  }

  return {
    expanded: String(raw.expanded),
    mode: raw.mode || mode,
    model: raw.model || "unknown",
    generatedAt: raw.generatedAt || new Date().toISOString(),
  };
}
