// src/pages/Summaries.jsx
import GlassCard from "../components/GlassCard";

const summaries = [
  { title: "Meeting_summary_jan.pdf", status: "Ready", created: "Jan 12" },
  { title: "Lecture_05_recording.mp4", status: "Drafting", created: "Feb 03" },
  { title: "Article_deepwork.html", status: "Ready", created: "Feb 10" },
];

const statusColors = {
  Ready: "bg-emerald-500/15 text-emerald-300 border-emerald-500/40",
  Drafting: "bg-amber-500/15 text-amber-300 border-amber-500/40",
};

export default function Summaries() {
  return (
    <div className="space-y-8">
      <header>
        <h1 className="text-2xl font-semibold text-white">AI Summaries</h1>
        <p className="text-gray-400 text-sm mt-1">
          Quick overviews of your long documents, recordings, and notes.
        </p>
      </header>

      <GlassCard>
        <div className="flex justify-between items-center mb-4">
          <p className="text-sm text-gray-400">
            Recent summaries generated by NoteStream AI.
          </p>
          <button
            onClick={() => alert("Open bulk upload / summarize flow")}
            className="text-xs px-3 py-1 rounded-full bg-indigo-600/80 hover:bg-indigo-500 text-white"
          >
            + Summarize New File
          </button>
        </div>

        <div className="space-y-3">
          {summaries.map((s, i) => (
            <div
              key={i}
              className="flex items-center justify-between bg-[#101016] border border-[#26262c] rounded-xl px-4 py-3 text-sm hover:border-indigo-500/40 transition"
            >
              <div>
                <p className="text-gray-100">{s.title}</p>
                <p className="text-[11px] text-gray-500 mt-0.5">
                  Created {s.created}
                </p>
              </div>
              <div className="flex items-center gap-3">
                <span
                  className={`text-[11px] px-2 py-1 rounded-full border ${
                    statusColors[s.status]
                  }`}
                >
                  {s.status}
                </span>
                <button
                  className="text-xs text-indigo-300 hover:text-indigo-200"
                  onClick={() => alert(`Open summary: ${s.title}`)}
                >
                  View
                </button>
                <button
                  className="text-xs text-gray-400 hover:text-gray-200"
                  onClick={() => alert(`Regenerate summary: ${s.title}`)}
                >
                  Regenerate
                </button>
              </div>
            </div>
          ))}
        </div>
      </GlassCard>
    </div>
  );
}
